### ISSUE TITLE
Audio not playing on Safari on iOS or MacOS

### ISSUE THREAD

**Issue by mikejamesthompson** [dracos/bach.js#1]
Nice work! I shall share with my music teacher/coder brother-in-law.

This didn't work for me on mobile from Twitter (clicking on an example you see "STOP" appear, but nothing else visual happens) but it did work on Chrome on desktop. Didn't work on desktop Safari either.

A bit of poking suggested that your code runs as expected and passes the data through to the `Conductor`, but the audio doesn't play.

Looks as if the `state` property of the `Conductor`'s `audioContext` is stuck on suspended, due to the issue (or Apple design decision) described in this post: https://hackernoon.com/unlocking-web-audio-the-smarter-way-8858218c0e09.

**Comment by dracos** [comment]
Hi, thanks and sorry for the delay. I've fixed this by pre-downloading all the data, so that when you click it can instantly play and bypass Safari's oh-you-fetched-some-data-from-the-internet-so-it's-async-audio protection. So should be okay everywhere now hopefully!
